
import static com.sun.webkit.perf.WCFontPerfLogger.reset;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.Statement;
import java.util.Date;
import javax.swing.JOptionPane;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author DELL
 */
public class books extends javax.swing.JFrame {
   Connection con = null;
   Statement stmt = null;
   ResultSet rs = null;

    /**
     * Creates new form books
     */
    public books() {
        initComponents();
        con = databaseconnection.connection();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        bookid = new javax.swing.JTextField();
        authur = new javax.swing.JTextField();
        year = new javax.swing.JTextField();
        quantity = new javax.swing.JTextField();
        genre = new javax.swing.JComboBox<>();
        booksubmit = new javax.swing.JButton();
        title = new javax.swing.JTextField();
        reset1 = new javax.swing.JButton();
        update1 = new javax.swing.JButton();
        search1 = new javax.swing.JButton();
        delete1 = new javax.swing.JButton();
        back = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        jLabel1.setText("Books");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 11, -1, -1));
        jPanel1.add(bookid, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 80, 410, 30));
        jPanel1.add(authur, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 200, 410, 30));

        year.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                yearActionPerformed(evt);
            }
        });
        jPanel1.add(year, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 310, 410, 30));
        jPanel1.add(quantity, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 380, 410, 30));

        genre.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Fiction", "Mystery", "Novel", "Thriller" }));
        jPanel1.add(genre, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 260, 80, 30));

        booksubmit.setBackground(new java.awt.Color(153, 204, 255));
        booksubmit.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        booksubmit.setText("Submit");
        booksubmit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                booksubmitActionPerformed(evt);
            }
        });
        jPanel1.add(booksubmit, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 440, -1, -1));
        jPanel1.add(title, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 140, 410, 30));

        reset1.setBackground(new java.awt.Color(153, 204, 255));
        reset1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        reset1.setText("reset");
        reset1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                reset1ActionPerformed(evt);
            }
        });
        jPanel1.add(reset1, new org.netbeans.lib.awtextra.AbsoluteConstraints(750, 510, -1, -1));

        update1.setBackground(new java.awt.Color(153, 204, 255));
        update1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        update1.setText("Update");
        update1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                update1ActionPerformed(evt);
            }
        });
        jPanel1.add(update1, new org.netbeans.lib.awtextra.AbsoluteConstraints(740, 440, -1, -1));

        search1.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        search1.setText("Search");
        search1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                search1ActionPerformed(evt);
            }
        });
        jPanel1.add(search1, new org.netbeans.lib.awtextra.AbsoluteConstraints(850, 80, -1, -1));

        delete1.setBackground(new java.awt.Color(153, 204, 255));
        delete1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        delete1.setText("Delete");
        delete1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                delete1ActionPerformed(evt);
            }
        });
        jPanel1.add(delete1, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 440, -1, -1));

        back.setText("Back");
        back.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backActionPerformed(evt);
            }
        });
        jPanel1.add(back, new org.netbeans.lib.awtextra.AbsoluteConstraints(860, 20, -1, -1));

        jPanel2.setBackground(new java.awt.Color(153, 153, 255));
        jPanel2.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 1, 5, new java.awt.Color(0, 0, 0)));

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel2.setText("Book ID");

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel3.setText("Title");

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel4.setText("Authur");

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel5.setText("Genre");

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel6.setText("Publish Year");

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel7.setText("Quantity");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(60, 60, 60)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel3)
                    .addComponent(jLabel7)
                    .addComponent(jLabel2)
                    .addComponent(jLabel4)
                    .addComponent(jLabel6)
                    .addComponent(jLabel5))
                .addContainerGap(221, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addComponent(jLabel2)
                .addGap(33, 33, 33)
                .addComponent(jLabel3)
                .addGap(38, 38, 38)
                .addComponent(jLabel4)
                .addGap(28, 28, 28)
                .addComponent(jLabel5)
                .addGap(37, 37, 37)
                .addComponent(jLabel6)
                .addGap(48, 48, 48)
                .addComponent(jLabel7)
                .addContainerGap(214, Short.MAX_VALUE))
        );

        jPanel1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 60, 400, 560));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void yearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_yearActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_yearActionPerformed

    private void reset()
    {         
    bookid.setText("");
    title.setText("");
    authur.setText("");
    genre.setSelectedItem("");
    year.setText("");
    quantity.setText("");
    }
    
    private void booksubmitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_booksubmitActionPerformed
        // TODO add your handling code here:
        try
        {
        stmt = con.createStatement();
        
         int sBookid=Integer.parseInt(bookid.getText());
         String sTitle =title.getText();
         String sAuthur =authur.getText();
         String sGenre = (String) genre.getSelectedItem();
         int sYear = Integer.parseInt(year.getText());
         int sQuantity = Integer.parseInt(quantity.getText());
                  
         
        String query ="INSERT INTO books (bookid,title,authur,genre,year,quantity) VALUES (?,?,?,?,?,?)";
        PreparedStatement preparedStmt=con.prepareStatement(query);
        
        preparedStmt.setInt(1,sBookid);
        preparedStmt.setString(2,sTitle);
        preparedStmt.setString(3,sAuthur);
        preparedStmt.setString(4,sGenre);
        preparedStmt.setInt(5,sYear);
        preparedStmt.setInt(6,sQuantity);
        
        preparedStmt.execute();
        JOptionPane.showMessageDialog(null,"ADDED");
        }
        catch (Exception e)
                {
                System.out.println(e);
                }
    }//GEN-LAST:event_booksubmitActionPerformed

    private void reset1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_reset1ActionPerformed
        // TODO add your handling code here:
        reset();
    }//GEN-LAST:event_reset1ActionPerformed

    private void update1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_update1ActionPerformed
        // TODO add your handling code here:
try{
stmt = con.createStatement();
        
         int sBookid=Integer.parseInt(bookid.getText());
         String sTitle =title.getText();
         String sAuthur =authur.getText();
         String sGenre = (String) genre.getSelectedItem();
         int sYear = Integer.parseInt(year.getText());
         int sQuantity = Integer.parseInt(quantity.getText());
                  
         
        String query ="UPDATE books SET title=?, authur=?,genre=?,year=?,quantity=? WHERE bookid=?";
        PreparedStatement preparedStmt=con.prepareStatement(query);
        
       
        preparedStmt.setString(1,sTitle);
        preparedStmt.setString(2,sAuthur);
        preparedStmt.setString(3,sGenre);
        preparedStmt.setInt(4,sYear);
        preparedStmt.setInt(5,sQuantity);
        preparedStmt.setInt(6,sBookid);
        
        preparedStmt.executeUpdate();  
        JOptionPane.showMessageDialog(null,"UPDATED");
    
}
catch (Exception e)
{
System.out.println(e);
}
    }//GEN-LAST:event_update1ActionPerformed

    private void search1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_search1ActionPerformed
        // TODO add your handling code here:
        
        try{
        
            
                    stmt = con.createStatement();
            
            int sBookid = Integer.parseInt(bookid.getText());
            
            String query = "SELECT * FROM books";
            
            rs = stmt.executeQuery(query);
            
            while(rs.next())
            {
                if(sBookid == rs.getInt("bookid"))
                {

title.setText(rs.getString("title"));
authur.setText(rs.getString("authur"));
genre.setSelectedItem(rs.getString("genre"));
year.setText(String.format("%s", rs.getInt("year")));
quantity.setText(String.format(0 +  "%s", rs.getInt("quantity")));

                }
            }
        }
        catch (Exception e)
        {
        System.out.println(e);
        }
    }//GEN-LAST:event_search1ActionPerformed

    private void delete1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_delete1ActionPerformed
        // TODO add your handling code here:
        try{
        
            

            stmt = con.createStatement();
            
            int sBookid = Integer.parseInt(bookid.getText());
            
            String query = "DELETE FROM books WHERE bookid ='"+sBookid+"' ";
            
            stmt.executeUpdate(query);
            
            reset();
            JOptionPane.showMessageDialog(null, "DELETED");
            
            
            
        }
        catch(Exception e)
        {
        System.out.println(e);
        }
    }//GEN-LAST:event_delete1ActionPerformed

    private void backActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backActionPerformed
        // TODO add your handling code here:
        setVisible(false);
        allbooks view = new allbooks();
        view.setVisible(true);
    }//GEN-LAST:event_backActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(books.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(books.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(books.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(books.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new books().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField authur;
    private javax.swing.JButton back;
    private javax.swing.JTextField bookid;
    private javax.swing.JButton booksubmit;
    private javax.swing.JButton delete1;
    private javax.swing.JComboBox<String> genre;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JTextField quantity;
    private javax.swing.JButton reset1;
    private javax.swing.JButton search1;
    private javax.swing.JTextField title;
    private javax.swing.JButton update1;
    private javax.swing.JTextField year;
    // End of variables declaration//GEN-END:variables
}
